"""
Knowledge Base Sync Lambda
Syncs incident postmortems from DynamoDB to S3 for Bedrock Knowledge Base
"""

import json
import os
import boto3
from datetime import datetime
from typing import Dict, List

s3 = boto3.client('s3')
dynamodb = boto3.client('dynamodb')
bedrock_agent = boto3.client('bedrock-agent')

KNOWLEDGE_BASE_ID = os.environ['KNOWLEDGE_BASE_ID']
DATA_SOURCE_ID = os.environ['DATA_SOURCE_ID']
S3_BUCKET = os.environ['S3_BUCKET']


def handler(event, context):
    """
    Sync incidents to Knowledge Base
    """
    print(f"Starting Knowledge Base sync for KB: {KNOWLEDGE_BASE_ID}")
    
    # Get all incidents from DynamoDB
    incidents = get_all_incidents()
    print(f"Found {len(incidents)} incidents to sync")
    
    # Generate postmortems and upload to S3
    synced_count = 0
    for incident in incidents:
        try:
            postmortem = generate_postmortem(incident)
            upload_to_s3(incident['incident_id']['S'], postmortem)
            synced_count += 1
        except Exception as e:
            print(f"Error syncing incident {incident.get('incident_id', {}).get('S', 'unknown')}: {e}")
    
    print(f"Synced {synced_count} incidents to S3")
    
    # Trigger ingestion job
    try:
        response = bedrock_agent.start_ingestion_job(
            knowledgeBaseId=KNOWLEDGE_BASE_ID,
            dataSourceId=DATA_SOURCE_ID
        )
        ingestion_job_id = response['ingestionJob']['ingestionJobId']
        print(f"Started ingestion job: {ingestion_job_id}")
        
        return {
            'statusCode': 200,
            'body': json.dumps({
                'synced_count': synced_count,
                'ingestion_job_id': ingestion_job_id
            })
        }
    except Exception as e:
        print(f"Error starting ingestion job: {e}")
        return {
            'statusCode': 500,
            'body': json.dumps({'error': str(e)})
        }


def get_all_incidents() -> List[Dict]:
    """Get all incidents from DynamoDB"""
    incidents = []
    
    try:
        response = dynamodb.scan(
            TableName='aiops-incidents',
            Limit=1000  # Limit to recent incidents
        )
        incidents = response.get('Items', [])
        
        # Handle pagination
        while 'LastEvaluatedKey' in response and len(incidents) < 1000:
            response = dynamodb.scan(
                TableName='aiops-incidents',
                ExclusiveStartKey=response['LastEvaluatedKey'],
                Limit=1000 - len(incidents)
            )
            incidents.extend(response.get('Items', []))
        
        return incidents
    except Exception as e:
        print(f"Error getting incidents: {e}")
        return []


def generate_postmortem(incident: Dict) -> str:
    """Generate postmortem document from incident"""
    incident_id = incident.get('incident_id', {}).get('S', 'unknown')
    timestamp = incident.get('incident_timestamp', {}).get('S', 'unknown')
    resource_type = incident.get('resource_type', {}).get('S', 'unknown')
    resource_id = incident.get('resource_id', {}).get('S', 'unknown')
    
    # Parse triage results
    triage_results = incident.get('triage_results', {}).get('S', '{}')
    try:
        triage = json.loads(triage_results)
        classification = triage.get('classification', 'UNKNOWN')
        severity = triage.get('severity_score', 0)
    except:
        classification = 'UNKNOWN'
        severity = 0
    
    # Parse remediation results
    remediation_results = incident.get('remediation_results', {}).get('S', '{}')
    try:
        remediation = json.loads(remediation_results)
        remediation_status = remediation.get('status', 'unknown')
    except:
        remediation_status = 'unknown'
    
    # Generate markdown postmortem
    postmortem = f"""# Incident Postmortem: {incident_id}

## Summary
- **Incident ID:** {incident_id}
- **Timestamp:** {timestamp}
- **Resource Type:** {resource_type}
- **Resource ID:** {resource_id}
- **Classification:** {classification}
- **Severity:** {severity}/10

## What Happened
An incident was detected on {resource_type} resource {resource_id} at {timestamp}.

The incident was classified as {classification} with a severity score of {severity}/10.

## Root Cause
Resource: {resource_type}/{resource_id}

## Resolution
Remediation status: {remediation_status}

## Lessons Learned
- Incident type: {classification}
- Resource affected: {resource_type}
- Automated remediation: {remediation_status}

## Action Items
- Review similar incidents for patterns
- Update runbooks if needed
- Monitor for recurrence

---
*This postmortem was automatically generated by the AIOps system.*
"""
    
    return postmortem


def upload_to_s3(incident_id: str, content: str):
    """Upload postmortem to S3"""
    key = f"postmortems/{incident_id}.md"
    
    s3.put_object(
        Bucket=S3_BUCKET,
        Key=key,
        Body=content.encode('utf-8'),
        ContentType='text/markdown',
        Metadata={
            'incident_id': incident_id,
            'generated_at': datetime.utcnow().isoformat()
        }
    )
    
    print(f"Uploaded postmortem to s3://{S3_BUCKET}/{key}")
